name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash -l {0}

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Mamba install dependencies
      run: mamba install python=${{ matrix.python-version }} pip nodejs jupyter-packaging

    - name: Mamba install JupyterLab 3
      run: mamba install jupyterlab=3 ipywidgets=7.6

    - name: Install here-map-widget-for-jupyter
      run: |
        npm config set @here:registry https://repo.platform.here.com/artifactory/api/npm/here-node/
        cd js
        npm install --legacy-peer-deps
        npm run build
        cd ..
        pip install .[dev]

    - name: Check installation files
      run: |
        test -d $CONDA_PREFIX/share/jupyter/nbextensions/map-widget-for-jupyter
        test -f $CONDA_PREFIX/share/jupyter/nbextensions/map-widget-for-jupyter/extension.js
        test -f $CONDA_PREFIX/share/jupyter/nbextensions/map-widget-for-jupyter/index.js
        test -d $CONDA_PREFIX/share/jupyter/labextensions/@here/map-widget-for-jupyter
        test -f $CONDA_PREFIX/share/jupyter/labextensions/@here/map-widget-for-jupyter/package.json

    - name: Lint check
      run: make lint

    - name: Import check
      run: python -c 'import here_map_widget'

    - name: Build the package (Only on Linux for saving time)
      if: matrix.os == 'ubuntu-latest'
      run: |
        python setup.py sdist bdist_wheel

    - name: Build docs (Only on Linux for saving time)
      if: matrix.os == 'ubuntu-latest'
      env:
        XYZ_TOKEN: ${{ secrets.XYZ_TOKEN }}
        LS_API_KEY: ${{ secrets.LS_API_KEY }}
      run: |
        mamba install sphinx sphinx_rtd_theme
        pip install -r docs/requirements.txt
        cd docs
        make html
